### ISSUE TITLE
Purged CSS output larger when using JIT and Tailwind plugins in Next.js

### ISSUE THREAD

**Issue by wKovacs64** [tailwindlabs/tailwindcss-jit#100]
Hi again. I just noticed the build output seems to include more CSS when using `@tailwindcss/jit` (vs. `tailwindcss`) and a plugin like `@tailwindcss/forms`.

`tailwindcss`: 1.67 kB Next.js estimate (4.8 kB on disk)
`@tailwindcss/jit`: 2.19 kB Next.js estimate (7.5 kB on disk)

I ran the production CSS files (resulting from `next build`) through prettier for easier reviewing:

- [non-jit.prettier.css](https://github.com/wKovacs64/tw-jit-next/blob/ece271387109d1e8b9f2a8aaaf3b49915a9525c3/non-jit.prettier.css)
- [jit.prettier.css](https://github.com/wKovacs64/tw-jit-next/blob/ece271387109d1e8b9f2a8aaaf3b49915a9525c3/jit.prettier.css)

It looks like most of the additional stuff consists of unused rules from `@tailwindcss/forms`?

**tailwind.config.js**

```
const tailwindForms = require('@tailwindcss/forms');

module.exports = {
  darkMode: false,
  plugins: [tailwindForms],
  purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
};
```

**postcss.config.js**

```
module.exports = {
  plugins: {
    '@tailwindcss/jit': {},
    autoprefixer: {},
  },
};
```

**Markup**

```html
<div>
  <label>
    <span>Some input:</span>
    <input type="text" />
  </label>
</div>
```

Full reproduction: https://github.com/wKovacs64/tw-jit-next

P.S. I'm certainly not complaining over less than 1 kB CSS difference, but figured it might be a problem in larger projects. 😅

**Comment by adamwathan** [comment]
Hey! Yeah this is currently expected, we do not dynamically generate anything except classes currently. This is something we expect to improve over time but starting conservative — I'd rather include a little bit of unused CSS than accidentally not include some important CSS, haha. Since we aren't using purge now we sort of have to reimplement the same overall principles ourselves, so keeping it simple to start.

So right now, any selectors that don't include classes are _always_ included in the output 👍  Going to close as intended behavior for now but definitely plan to play with optimizing this more down the road.

**Comment by wKovacs64** [comment]
@adamwathan OK, sweet 👍 Thanks for the explanation!
