### ISSUE TITLE
Error: resolve-url-loader: CSS error with arbitrary value support

### ISSUE THREAD

**Issue by robylosa94** [tailwindlabs/tailwindcss-jit#109]
### What version of @tailwindcss/jit are you using?

v0.1.3

### What version of Node.js are you using?

v.12.20.0

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/robylosa94/tailwindjit-issue.git

I'm using the arbitrary value support functionality like this:

<img width="577" alt="Schermata 2021-03-18 alle 14 56 05" src="https://user-images.githubusercontent.com/12608128/111637813-12af8a80-87fa-11eb-91cb-108840c3cf10.png">

In development everything is alright, but on build goes wrong the resolve-url-loader package:

<img width="987" alt="Schermata 2021-03-18 alle 14 58 17" src="https://user-images.githubusercontent.com/12608128/111638514-b0a35500-87fa-11eb-9508-4ebf13037d6a.png">

I'm using webpack 4 and sass.

Thanks for the support!

**Comment by adamwathan** [comment]
Hey! Please provide a reproduction as requested — the reproduction field is required because it makes it a lot easier to troubleshoot stuff if we can just clone it down vs. creating it all from scratch.

**Comment by robylosa94** [comment]
> Hey! Please provide a reproduction as requested — the reproduction field is required because it makes it a lot easier to troubleshoot stuff if we can just clone it down vs. creating it all from scratch.

**Comment by robylosa94** [comment]
@adamwathan Sorry, I have updated the request!

**Comment by valse** [comment]
Hi, I have the same issue on the last 0.1.5 version too

**Comment by adamwathan** [comment]
Can you test this on v0.1.7 and see if it fixes your issue? Thanks!

**Comment by valse** [comment]
> Can you test this on v0.1.7 and see if it fixes your issue? Thanks!

I tested it with the v0.1.7 but I have the same build error, thank you for your help!

**Comment by adamwathan** [comment]
This is a tricky one to nail down but in my testing this _only_ happens with Sass, and is not an issue if you are writing (Post)CSS. I took the reproduction repository and converted `Grid.module.scss` to `Grid.module.css` and refactored any Sass-specific syntax (like removing nesting) and the error went away.

Unfortunately I don't expect there is anything we can do on our side to fix this since it seems to be something to do with Sass specifically, so going to have to close without taking any action on it and recommend either not using Sass (I personally would recommend this, it's not worth the extra complexity/build slow down), or just writing regular CSS for these situations:

```diff
  .root {
-   @apply top-[30%];
+   top: 30%;
  }
```
