### ISSUE TITLE
Generate arbitrary styles without writing custom CSS

### ISSUE THREAD

**Issue by k16e-me** [tailwindlabs/tailwindcss-jit#121]
### What version of @tailwindcss/jit are you using?

v0.1.4

### What version of Node.js are you using?

v14.15.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://www.loom.com/share/4ea348de8342480eb00912acb5974ddb

Doesn't seem to work with other CSS properties except "top" or "left" or any `position` offset.

**Comment by roberthamel** [comment]
Hi, I watched your clip. 

`top-[640px]` is working because it is a valid tailwind prefix: [https://tailwindcss.com/docs/top-right-bottom-left](https://tailwindcss.com/docs/top-right-bottom-left)

`max-height-[640px]` is not a tailwind prefix. try `max-h-[640px]` [https://tailwindcss.com/docs/max-height](https://tailwindcss.com/docs/max-height)

Same with `margin-[56px]`. Try `m-[56px]` instead. [https://tailwindcss.com/docs/margin](https://tailwindcss.com/docs/margin).

**Comment by k16e-me** [comment]
Thanks, @roberthamel. Ye got it!
