### ISSUE TITLE
No new classes are created since JIT install

### ISSUE THREAD

**Issue by APB9785** [tailwindlabs/tailwindcss-jit#140]
### What version of @tailwindcss/jit are you using?

v0.1.6

### What version of Node.js are you using?

v15.7.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

I am building on Elixir/Phoenix stack

Ever since installing the JIT installer, no new classes are being generated.  I can add a new class <div class"text-2xl">text</div> and it will only be regular sized.  But if I use a class that was already generated before the JIT install, such as "text-xl", then it works fine.

I am using the Elixir framework called Phoenix, which runs Node and handles all JS-related tasks automatically, only requiring the developer to write Elixir and HTML.  Many Phoenix developers use Tailwind, and it works very well "out of the box" for our stack.  It's only been since I installed the JIT compiler (using the instructions on the GitHub readme), that this issue has been occurring.

**Comment by APB9785** [comment]
Simply removing the JIT compiler from postcss.config.js and returning to plugins: { tailwindcss: {} ... } resolves the issue for me.  So either JIT breaks Phoenix compatibility somehow, or the installation instructions here are not sufficient.  I will keep looking into the issue and report back here with any findings.

**Comment by adamwathan** [comment]
Hey! Please provide a reproduction repository so we can actually clone it down and troubleshoot it.

**Comment by adamwathan** [comment]
Going to close since a reproduction was not provided, happy to help though if you can open a new issue that includes the required field, thanks ❤️

**Comment by rktjmp** [comment]
https://github.com/rktjmp/phx-tailwindcssjit

Here is a basic repro, but phoenix comes with some baggage (needs postgres, etc, you probably need a docker repro really).

Not sure how much of it is tailwind vs phx.

It actually does work, sort of:

- It _does_ generate code for the `disabled:opacity-75` example
- It _doesnt_ generate code for the custom colour or positioning (`[...]` syntax).
- It only updates when editing the css file instead of noticing template changes
  - not really a tw issue (I think?)
- it doesn't apply any "reset css"
  - doesn't replace my "@tailwind base" line in css file, not sure it these are still needed

Note that Phoenix uses webpack4 which may be an issue.

Willing to do the heavy lifting where I can, but not quite sure where I should be looking, webpack/js-builders not really my jam.

Probably worth renaming this issue to something like "Phoenix integration doesn't generate all classes" or something since that's what it's really about.

**Comment by APB9785** [comment]
Any classes generated before the JIT install work fine for me.  It's only new classes added after the JIT install, which are not generated.  An example repo should be simple if you have Erlang/Elixir/Phoenix installed, just use run the app generator "mix phx.new app_name" at CLI.

**Comment by APB9785** [comment]
This is likely an issue with the installation instructions missing a step which is required for other frameworks such as Phoenix.
