### ISSUE TITLE
How to enable with CRA and CRACO (PostCSS 7)?

### ISSUE THREAD

**Issue by OmerWow** [tailwindlabs/tailwindcss-jit#17]
Hi,

So because CRA doesn't support PostCSS8, you recommend (it's probably mandatory and not a recommendation) to install CRACO and use it to configure Tailwind.
Unfortunately I get an error message after trying to use the JIT compiler (changing the CRACO config to the jit module) that the jit only supports PostCSS8.

Can I really not use it because I'm using CRA?

**Comment by adamwathan** [comment]
Currently the JIT project only supports PostCSS 8, correct. We may do a compat build like we do for Tailwind but not a priority right now.

I would recommend using [Vite](https://vitejs.dev) instead of CRA if you want something similar in the mean time personally — it is much faster and works beautifully with React out of the box.
