### ISSUE TITLE
Opacity class is not working on svg elements

### ISSUE THREAD

**Issue by fasetto** [tailwindlabs/tailwindcss-jit#170]
### What version of @tailwindcss/jit are you using?

v0.1.12

### What version of Node.js are you using?

v12.6.2

### What browser are you using?

Edge

### What operating system are you using?

Windows

### Reproduction repository

Sorry.

`opacity-*` class is not working on svg elements like circle, path.

**Comment by adamwathan** [comment]
Hey! This definitely won't be specific to the JIT repo but it works as expected for me:

https://play.tailwindcss.com/1xFpO2Ojk4

(not using JIT in that demo but the CSS that's generated is identical)

Going to close since I can't reproduce, feel free to open a new issue but you'll have to include a reproduction otherwise I can't really help.
