### ISSUE TITLE
Not all variants are available (Tailwind + Vite + React)

### ISSUE THREAD

**Issue by edgarasben** [tailwindlabs/tailwindcss-jit#171]
### What version of @tailwindcss/jit are you using?

 v0.1.13

### What version of Node.js are you using?

v14.15.1

### What browser are you using?

Safari

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/edgarasben/bulletproof-ui/

I am trying to access all variants from JIT documentation, but they do not seem to work.

I've tried these few from the documentation
`<input class="disabled:opacity-75">`
and
`<button class="md:dark:disabled:focus:hover:bg-gray-400">`

My setup is: Tailwind + Vite + React

What am I getting wrong here? Do I need to extra configuration?

**Comment by adamwathan** [comment]
Hey! I can't reproduce, seems to be working as expected — when I add the disabled attribute to the input the `disabled:opacity-25` class kicks in just like it's supposed to:

https://user-images.githubusercontent.com/4323180/112728421-9ace1800-8efd-11eb-93e2-2922a0d604be.mov

Same with the button, once I add the `dark` class to the HTML element and make the button disabled, the styles kick in on hover+focus at the md breakpoint:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/4323180/112728541-35c6f200-8efe-11eb-9938-4b485cf9817a.png">

Going to close since I think this is maybe just expecting the feature to work differently — feel free to open another issue with a really clear/minimal reproduction though if I'm misunderstanding.

**Comment by edgarasben** [comment]
Hi, Adam! You are right, it's working perfectly. It's just me getting confused about the `disabled` state. Thank you!
