### ISSUE TITLE
Dark mode incompatible with bg-opacity classes

### ISSUE THREAD

**Issue by laugharn** [tailwindlabs/tailwindcss-jit#27]
When using `bg-* dark:bg-*` with `bg-opacity-*`, the opacity class is ignored in dark mode. This works correctly in AOT/classic mode.

Reproduction repo: https://github.com/laugharn/jit-repro

**Comment by adamwathan** [comment]
Hey thanks for opening this! This is actually the same behavior as in AOT mode, see similar issue with previous discussion here:

https://github.com/tailwindlabs/tailwindcss/issues/2966

Some kinks in there still around how the behavior changes depending on which `mode` you use — hopefully something we can think of a solution for in v3.

Going to close because unless I'm misunderstanding (I might be, apologies if so!) this is actually intended at the moment 👍🏻

**Comment by laugharn** [comment]
@adamwathan that's interesting, in `darkMode: media` on 2.0.3 it works as I would expect, as seen in the backdrop-filter'd overlay in the attached screenshots:

### Light Mode `bg-black`

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1186188/111225309-a2acc480-85ad-11eb-8515-439ee8a5b587.png">

### Dark Mode `dark:bg-white`

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1186188/111225359-b3f5d100-85ad-11eb-9514-c88327c79deb.png">
Dark mode

Should I assume this will stop working? My use case isn't very complicated and I'll refactor both modes to key off of a neutral gray instead, but I would consider this breaking-ish.
