### ISSUE TITLE
De-duping functionally identical calls

### ISSUE THREAD

**Issue by andparsons** [tailwindlabs/tailwindcss-jit#44]
Is there any way I can be warned if I have 2 functionally identical calls,

Eg: `sm:hover:disabled:bg-red-500` & `sm:disabled:hover:bg-red-500`

**Comment by andparsons** [comment]
In the same vain, perhaps a warning for using something like `w-[100%]` when `w-full` exists?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

For your first question, yep we will make sure that you get notified of this using errors/warnings.
For your second question, while it is a nice idea, it could degrade performance (haven't measured it yet). Because you would have to check the contents of each existing rule and each rule you are applying.

We are also generating on demand, which means that we don't even know when certain rules that have been used yet (if we knew, then we would be back in AOT land). So long story short, if you used `w-full` in one spot and use `w-[100%]` in another, we _could_ detect it, otherwise it is a bit more challenging.
