### ISSUE TITLE
How to run incremental rebuilds?

### ISSUE THREAD

**Issue by m-allanson** [tailwindlabs/tailwindcss-jit#90]
Is it possible to do incremental rebuilds without an external build tool?

I'm running `@tailwindcss/jit` like this:

`TAILWIND_MODE=watch postcss src/styles.css -o dist/styles.css`

The task builds my CSS once and then runs forever as if it's watching for file changes. However, it doesn't update `dist/styles.css` when I make further changes to my files.

I expected the watch mode to re-compile my CSS when I make changes to my templates, but that's not happening.

What's the right approach to do this?

## Reproduction steps:

- Clone https://github.com/m-allanson/tailwind-jit-example 
- Run `npm install`
- Run `npm run css:watch`
- Note compiled CSS output to `dist/styles.css`
- Add a new class to `src/index.html`
- Note that `dist/styles.css` does not update with the new class

**Comment by adamwathan** [comment]
Hey! You're missing the `-w` flag to PostCSS to tell it to run in watcher mode:

```
TAILWIND_MODE=watch postcss src/styles.css -o dist/styles.css -w
```

Throw `--verbose` on there too if you are interested in seeing the rebuild times 👍🏻 

The `TAILWIND_MODE` thing doesn't actually enable your watcher, it just tells Tailwind whether you are running a watcher or not so we can do some things a little differently internally. This is unfortunate but necessary because there's no way for us to reliably auto-detect if you are doing a one-off build or a watch process.

**Comment by m-allanson** [comment]
That did it, thank you! I've updated my example with your suggested changes.
